name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create config file
        run: ./generate.sh
      - uses: actions/upload-artifact@v2
        with:
          name: prevent-brain-upgrade.conf
          path: prevent-brain-upgrade.conf
